<?PHP

$boards = explode("\n", "/tmp/aa/zephyr/boards/xtensa/xt-sim/xt-sim_defconfig
/tmp/aa/zephyr/boards/xtensa/qemu_xtensa/qemu_xtensa_defconfig
/tmp/aa/zephyr/boards/xtensa/olimex_esp32_evb/olimex_esp32_evb_defconfig
/tmp/aa/zephyr/boards/xtensa/odroid_go/odroid_go_defconfig
/tmp/aa/zephyr/boards/xtensa/nxp_adsp_imx8x/nxp_adsp_imx8x_defconfig
/tmp/aa/zephyr/boards/xtensa/nxp_adsp_imx8m/nxp_adsp_imx8m_defconfig
/tmp/aa/zephyr/boards/xtensa/nxp_adsp_imx8/nxp_adsp_imx8_defconfig
/tmp/aa/zephyr/boards/xtensa/intel_adsp_cavs25/intel_adsp_cavs25_defconfig
/tmp/aa/zephyr/boards/xtensa/intel_adsp_cavs25/intel_adsp_cavs25_tgph_defconfig
/tmp/aa/zephyr/boards/xtensa/intel_adsp_cavs20/intel_adsp_cavs20_jsl_defconfig
/tmp/aa/zephyr/boards/xtensa/intel_adsp_cavs20/intel_adsp_cavs20_defconfig
/tmp/aa/zephyr/boards/xtensa/intel_adsp_cavs18/intel_adsp_cavs18_defconfig
/tmp/aa/zephyr/boards/xtensa/intel_adsp_cavs15/intel_adsp_cavs15_defconfig
/tmp/aa/zephyr/boards/xtensa/intel_adsp_ace15_mtpm/intel_adsp_ace15_mtpm_defconfig
/tmp/aa/zephyr/boards/xtensa/heltec_wifi_lora32_v2/heltec_wifi_lora32_v2_defconfig
/tmp/aa/zephyr/boards/xtensa/esp_wrover_kit/esp_wrover_kit_defconfig
/tmp/aa/zephyr/boards/xtensa/esp32s2_saola/esp32s2_saola_defconfig
/tmp/aa/zephyr/boards/xtensa/esp32_net/esp32_net_defconfig
/tmp/aa/zephyr/boards/xtensa/esp32/esp32_defconfig
/tmp/aa/zephyr/boards/x86/up_squared/up_squared_defconfig
/tmp/aa/zephyr/boards/x86/qemu_x86/qemu_x86_xip_defconfig
/tmp/aa/zephyr/boards/x86/qemu_x86/qemu_x86_virt_defconfig
/tmp/aa/zephyr/boards/x86/qemu_x86/qemu_x86_tiny_defconfig
/tmp/aa/zephyr/boards/x86/qemu_x86/qemu_x86_nopae_defconfig
/tmp/aa/zephyr/boards/x86/qemu_x86/qemu_x86_nommu_defconfig
/tmp/aa/zephyr/boards/x86/qemu_x86/qemu_x86_nokpti_defconfig
/tmp/aa/zephyr/boards/x86/qemu_x86/qemu_x86_lakemont_defconfig
/tmp/aa/zephyr/boards/x86/qemu_x86/qemu_x86_defconfig
/tmp/aa/zephyr/boards/x86/qemu_x86/qemu_x86_64_nokpti_defconfig
/tmp/aa/zephyr/boards/x86/qemu_x86/qemu_x86_64_defconfig
/tmp/aa/zephyr/boards/x86/ehl_crb/ehl_crb_sbl_defconfig
/tmp/aa/zephyr/boards/x86/ehl_crb/ehl_crb_defconfig
/tmp/aa/zephyr/boards/x86/acrn/acrn_ehl_crb_defconfig
/tmp/aa/zephyr/boards/x86/acrn/acrn_defconfig
/tmp/aa/zephyr/boards/sparc/qemu_leon3/qemu_leon3_defconfig
/tmp/aa/zephyr/boards/sparc/gr716a_mini/gr716a_mini_defconfig
/tmp/aa/zephyr/boards/sparc/generic_leon3/generic_leon3_defconfig
/tmp/aa/zephyr/boards/riscv/tlsr9518adk80d/tlsr9518adk80d_defconfig
/tmp/aa/zephyr/boards/riscv/rv32m1_vega/rv32m1_vega_zero_riscy_defconfig
/tmp/aa/zephyr/boards/riscv/rv32m1_vega/rv32m1_vega_ri5cy_defconfig
/tmp/aa/zephyr/boards/riscv/qemu_riscv64/qemu_riscv64_smp_defconfig
/tmp/aa/zephyr/boards/riscv/qemu_riscv64/qemu_riscv64_defconfig
/tmp/aa/zephyr/boards/riscv/qemu_riscv32e/qemu_riscv32e_defconfig
/tmp/aa/zephyr/boards/riscv/qemu_riscv32/qemu_riscv32_xip_defconfig
/tmp/aa/zephyr/boards/riscv/qemu_riscv32/qemu_riscv32_smp_defconfig
/tmp/aa/zephyr/boards/riscv/qemu_riscv32/qemu_riscv32_defconfig
/tmp/aa/zephyr/boards/riscv/neorv32/neorv32_defconfig
/tmp/aa/zephyr/boards/riscv/mpfs_icicle/mpfs_icicle_defconfig
/tmp/aa/zephyr/boards/riscv/m2gl025_miv/m2gl025_miv_defconfig
/tmp/aa/zephyr/boards/riscv/longan_nano/longan_nano_lite_defconfig
/tmp/aa/zephyr/boards/riscv/longan_nano/longan_nano_defconfig
/tmp/aa/zephyr/boards/riscv/litex_vexriscv/litex_vexriscv_defconfig
/tmp/aa/zephyr/boards/riscv/it8xxx2_evb/it8xxx2_evb_defconfig
/tmp/aa/zephyr/boards/riscv/icev_wireless/icev_wireless_defconfig
/tmp/aa/zephyr/boards/riscv/hifive_unmatched/hifive_unmatched_defconfig
/tmp/aa/zephyr/boards/riscv/hifive_unleashed/hifive_unleashed_defconfig
/tmp/aa/zephyr/boards/riscv/hifive1_revb/hifive1_revb_defconfig
/tmp/aa/zephyr/boards/riscv/hifive1/hifive1_defconfig
/tmp/aa/zephyr/boards/riscv/gd32vf103v_eval/gd32vf103v_eval_defconfig
/tmp/aa/zephyr/boards/riscv/gd32vf103c_starter/gd32vf103c_starter_defconfig
/tmp/aa/zephyr/boards/riscv/esp32c3_devkitm/esp32c3_devkitm_defconfig
/tmp/aa/zephyr/boards/riscv/beaglev_starlight_jh7100/beaglev_starlight_jh7100_defconfig
/tmp/aa/zephyr/boards/riscv/adp_xc7k_ae350/adp_xc7k_ae350_defconfig
/tmp/aa/zephyr/boards/posix/nrf52_bsim/nrf52_bsim_defconfig
/tmp/aa/zephyr/boards/posix/native_posix/native_posix_defconfig
/tmp/aa/zephyr/boards/posix/native_posix/native_posix_64_defconfig
/tmp/aa/zephyr/boards/nios2/qemu_nios2/qemu_nios2_defconfig
/tmp/aa/zephyr/boards/nios2/altera_max10/altera_max10_defconfig
/tmp/aa/zephyr/boards/mips/qemu_malta/qemu_malta_defconfig
/tmp/aa/zephyr/boards/mips/qemu_malta/qemu_malta_be_defconfig
/tmp/aa/zephyr/boards/arm64/xenvm/xenvm_gicv3_defconfig
/tmp/aa/zephyr/boards/arm64/xenvm/xenvm_defconfig
/tmp/aa/zephyr/boards/arm64/qemu_cortex_a53/qemu_cortex_a53_xip_defconfig
/tmp/aa/zephyr/boards/arm64/qemu_cortex_a53/qemu_cortex_a53_smp_defconfig
/tmp/aa/zephyr/boards/arm64/qemu_cortex_a53/qemu_cortex_a53_defconfig
/tmp/aa/zephyr/boards/arm64/nxp_ls1046ardb/nxp_ls1046ardb_smp_4cores_defconfig
/tmp/aa/zephyr/boards/arm64/nxp_ls1046ardb/nxp_ls1046ardb_smp_2cores_defconfig
/tmp/aa/zephyr/boards/arm64/nxp_ls1046ardb/nxp_ls1046ardb_defconfig
/tmp/aa/zephyr/boards/arm64/intel_socfpga_agilex_socdk/intel_socfpga_agilex_socdk_defconfig
/tmp/aa/zephyr/boards/arm64/imx8mp_evk/imx8mp_evk_jailhouse_defconfig
/tmp/aa/zephyr/boards/arm64/imx8mp_evk/imx8mp_evk_defconfig
/tmp/aa/zephyr/boards/arm64/imx8mm_evk/imx8mm_evk_jailhouse_defconfig
/tmp/aa/zephyr/boards/arm64/imx8mm_evk/imx8mm_evk_defconfig
/tmp/aa/zephyr/boards/arm64/fvp_baser_aemv8r/fvp_baser_aemv8r_smp_defconfig
/tmp/aa/zephyr/boards/arm64/fvp_baser_aemv8r/fvp_baser_aemv8r_defconfig
/tmp/aa/zephyr/boards/arm64/fvp_base_revc_2xaemv8a/fvp_base_revc_2xaemv8a_defconfig
/tmp/aa/zephyr/boards/arm64/bcm958402m2_a72/bcm958402m2_a72_defconfig
/tmp/aa/zephyr/boards/arm/zybo/zybo_defconfig
/tmp/aa/zephyr/boards/arm/xmc45_relax_kit/xmc45_relax_kit_defconfig
/tmp/aa/zephyr/boards/arm/xiao_ble/xiao_ble_defconfig
/tmp/aa/zephyr/boards/arm/we_proteus3ev_nrf52840/we_proteus3ev_nrf52840_defconfig
/tmp/aa/zephyr/boards/arm/we_proteus2ev_nrf52832/we_proteus2ev_nrf52832_defconfig
/tmp/aa/zephyr/boards/arm/we_ophelia1ev_nrf52805/we_ophelia1ev_nrf52805_defconfig
/tmp/aa/zephyr/boards/arm/waveshare_open103z/waveshare_open103z_defconfig
/tmp/aa/zephyr/boards/arm/warp7_m4/warp7_m4_defconfig
/tmp/aa/zephyr/boards/arm/v2m_musca_s1/v2m_musca_s1_ns_defconfig
/tmp/aa/zephyr/boards/arm/v2m_musca_s1/v2m_musca_s1_defconfig
/tmp/aa/zephyr/boards/arm/v2m_musca_b1/v2m_musca_b1_ns_defconfig
/tmp/aa/zephyr/boards/arm/v2m_musca_b1/v2m_musca_b1_defconfig
/tmp/aa/zephyr/boards/arm/v2m_beetle/v2m_beetle_defconfig
/tmp/aa/zephyr/boards/arm/usb_kw24d512/usb_kw24d512_defconfig
/tmp/aa/zephyr/boards/arm/udoo_neo_full_m4/udoo_neo_full_m4_defconfig
/tmp/aa/zephyr/boards/arm/ubx_evkninab4_nrf52833/ubx_evkninab4_nrf52833_defconfig
/tmp/aa/zephyr/boards/arm/ubx_evkninab3_nrf52840/ubx_evkninab3_nrf52840_defconfig
/tmp/aa/zephyr/boards/arm/ubx_evkninab1_nrf52832/ubx_evkninab1_nrf52832_defconfig
/tmp/aa/zephyr/boards/arm/ubx_evkannab1_nrf52832/ubx_evkannab1_nrf52832_defconfig
/tmp/aa/zephyr/boards/arm/ubx_bmd380eval_nrf52840/ubx_bmd380eval_nrf52840_defconfig
/tmp/aa/zephyr/boards/arm/ubx_bmd360eval_nrf52811/ubx_bmd360eval_nrf52811_defconfig
/tmp/aa/zephyr/boards/arm/ubx_bmd345eval_nrf52840/ubx_bmd345eval_nrf52840_defconfig
/tmp/aa/zephyr/boards/arm/ubx_bmd340eval_nrf52840/ubx_bmd340eval_nrf52840_defconfig
/tmp/aa/zephyr/boards/arm/ubx_bmd330eval_nrf52810/ubx_bmd330eval_nrf52810_defconfig
/tmp/aa/zephyr/boards/arm/ubx_bmd300eval_nrf52832/ubx_bmd300eval_nrf52832_defconfig
/tmp/aa/zephyr/boards/arm/twr_kv58f220m/twr_kv58f220m_defconfig
/tmp/aa/zephyr/boards/arm/twr_ke18f/twr_ke18f_defconfig
/tmp/aa/zephyr/boards/arm/thingy53_nrf5340/thingy53_nrf5340_cpunet_defconfig
/tmp/aa/zephyr/boards/arm/thingy53_nrf5340/thingy53_nrf5340_cpuapp_ns_defconfig
/tmp/aa/zephyr/boards/arm/thingy53_nrf5340/thingy53_nrf5340_cpuapp_defconfig
/tmp/aa/zephyr/boards/arm/thingy52_nrf52832/thingy52_nrf52832_defconfig
/tmp/aa/zephyr/boards/arm/teensy4/teensy41_defconfig
/tmp/aa/zephyr/boards/arm/teensy4/teensy40_defconfig
/tmp/aa/zephyr/boards/arm/tdk_robokit1/tdk_robokit1_defconfig
/tmp/aa/zephyr/boards/arm/swan_r5/swan_r5_defconfig
/tmp/aa/zephyr/boards/arm/stm32vl_disco/stm32vl_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32mp157c_dk2/stm32mp157c_dk2_defconfig
/tmp/aa/zephyr/boards/arm/stm32l562e_dk/stm32l562e_dk_ns_defconfig
/tmp/aa/zephyr/boards/arm/stm32l562e_dk/stm32l562e_dk_defconfig
/tmp/aa/zephyr/boards/arm/stm32l496g_disco/stm32l496g_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32l476g_disco/stm32l476g_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32l1_disco/stm32l1_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32h7b3i_dk/stm32h7b3i_dk_defconfig
/tmp/aa/zephyr/boards/arm/stm32h747i_disco/stm32h747i_disco_m7_defconfig
/tmp/aa/zephyr/boards/arm/stm32h747i_disco/stm32h747i_disco_m4_defconfig
/tmp/aa/zephyr/boards/arm/stm32h735g_disco/stm32h735g_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32g081b_eval/stm32g081b_eval_defconfig
/tmp/aa/zephyr/boards/arm/stm32g071b_disco/stm32g071b_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32g0316_disco/stm32g0316_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32f769i_disco/stm32f769i_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32f7508_dk/stm32f7508_dk_defconfig
/tmp/aa/zephyr/boards/arm/stm32f746g_disco/stm32f746g_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32f723e_disco/stm32f723e_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32f4_disco/stm32f4_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32f469i_disco/stm32f469i_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32f429i_disc1/stm32f429i_disc1_defconfig
/tmp/aa/zephyr/boards/arm/stm32f412g_disco/stm32f412g_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32f411e_disco/stm32f411e_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32f401_mini/stm32f401_mini_defconfig
/tmp/aa/zephyr/boards/arm/stm32f3_disco/stm32f3_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32f103_mini/stm32f103_mini_defconfig
/tmp/aa/zephyr/boards/arm/stm32f0_disco/stm32f0_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32f072b_disco/stm32f072b_disco_defconfig
/tmp/aa/zephyr/boards/arm/stm32f072_eval/stm32f072_eval_defconfig
/tmp/aa/zephyr/boards/arm/stm32f030_demo/stm32f030_demo_defconfig
/tmp/aa/zephyr/boards/arm/stm32_min_dev/stm32_min_dev_blue_defconfig
/tmp/aa/zephyr/boards/arm/stm32_min_dev/stm32_min_dev_black_defconfig
/tmp/aa/zephyr/boards/arm/stm32373c_eval/stm32373c_eval_defconfig
/tmp/aa/zephyr/boards/arm/stm3210c_eval/stm3210c_eval_defconfig
/tmp/aa/zephyr/boards/arm/steval_fcu001v1/steval_fcu001v1_defconfig
/tmp/aa/zephyr/boards/arm/sparkfun_thing_plus_nrf9160/sparkfun_thing_plus_nrf9160_ns_defconfig
/tmp/aa/zephyr/boards/arm/sparkfun_thing_plus_nrf9160/sparkfun_thing_plus_nrf9160_defconfig
/tmp/aa/zephyr/boards/arm/serpente/serpente_defconfig
/tmp/aa/zephyr/boards/arm/sensortile_box/sensortile_box_defconfig
/tmp/aa/zephyr/boards/arm/segger_trb_stm32f407/segger_trb_stm32f407_defconfig
/tmp/aa/zephyr/boards/arm/seeeduino_xiao/seeeduino_xiao_defconfig
/tmp/aa/zephyr/boards/arm/scobc_module1/scobc_module1_defconfig
/tmp/aa/zephyr/boards/arm/sam_v71_xult/sam_v71b_xult_defconfig
/tmp/aa/zephyr/boards/arm/sam_v71_xult/sam_v71_xult_defconfig
/tmp/aa/zephyr/boards/arm/sam_e70_xplained/sam_e70b_xplained_defconfig
/tmp/aa/zephyr/boards/arm/sam_e70_xplained/sam_e70_xplained_defconfig
/tmp/aa/zephyr/boards/arm/sam4s_xplained/sam4s_xplained_defconfig
/tmp/aa/zephyr/boards/arm/sam4l_ek/sam4l_ek_defconfig
/tmp/aa/zephyr/boards/arm/sam4e_xpro/sam4e_xpro_defconfig
/tmp/aa/zephyr/boards/arm/ruuvi_ruuvitag/ruuvi_ruuvitag_defconfig
/tmp/aa/zephyr/boards/arm/rpi_pico/rpi_pico_defconfig
/tmp/aa/zephyr/boards/arm/ronoth_lodev/ronoth_lodev_defconfig
/tmp/aa/zephyr/boards/arm/rm1xx_dvk/rm1xx_dvk_defconfig
/tmp/aa/zephyr/boards/arm/reel_board/reel_board_v2_defconfig
/tmp/aa/zephyr/boards/arm/reel_board/reel_board_defconfig
/tmp/aa/zephyr/boards/arm/rddrone_fmuk66/rddrone_fmuk66_defconfig
/tmp/aa/zephyr/boards/arm/rcar_h3ulcb/rcar_h3ulcb_cr7_defconfig
/tmp/aa/zephyr/boards/arm/rcar_h3_salvatorx/rcar_h3_salvatorx_cr7_defconfig
/tmp/aa/zephyr/boards/arm/rak5010_nrf52840/rak5010_nrf52840_defconfig
/tmp/aa/zephyr/boards/arm/rak4631_nrf52840/rak4631_nrf52840_defconfig
/tmp/aa/zephyr/boards/arm/quick_feather/quick_feather_defconfig
/tmp/aa/zephyr/boards/arm/qemu_cortex_r5/qemu_cortex_r5_defconfig
/tmp/aa/zephyr/boards/arm/qemu_cortex_m3/qemu_cortex_m3_defconfig
/tmp/aa/zephyr/boards/arm/qemu_cortex_m0/qemu_cortex_m0_defconfig
/tmp/aa/zephyr/boards/arm/qemu_cortex_a9/qemu_cortex_a9_defconfig
/tmp/aa/zephyr/boards/arm/pinnacle_100_dvk/pinnacle_100_dvk_defconfig
/tmp/aa/zephyr/boards/arm/pinetime_devkit0/pinetime_devkit0_defconfig
/tmp/aa/zephyr/boards/arm/pico_pi_m4/pico_pi_m4_defconfig
/tmp/aa/zephyr/boards/arm/particle_xenon/particle_xenon_defconfig
/tmp/aa/zephyr/boards/arm/particle_boron/particle_boron_defconfig
/tmp/aa/zephyr/boards/arm/particle_argon/particle_argon_defconfig
/tmp/aa/zephyr/boards/arm/pan1782_evb/pan1782_evb_defconfig
/tmp/aa/zephyr/boards/arm/pan1781_evb/pan1781_evb_defconfig
/tmp/aa/zephyr/boards/arm/pan1780_evb/pan1780_evb_defconfig
/tmp/aa/zephyr/boards/arm/pan1770_evb/pan1770_evb_defconfig
/tmp/aa/zephyr/boards/arm/olimexino_stm32/olimexino_stm32_defconfig
/tmp/aa/zephyr/boards/arm/olimex_stm32_p405/olimex_stm32_p405_defconfig
/tmp/aa/zephyr/boards/arm/olimex_stm32_h407/olimex_stm32_h407_defconfig
/tmp/aa/zephyr/boards/arm/olimex_stm32_h405/olimex_stm32_h405_defconfig
/tmp/aa/zephyr/boards/arm/olimex_stm32_h103/olimex_stm32_h103_defconfig
/tmp/aa/zephyr/boards/arm/olimex_stm32_e407/olimex_stm32_e407_defconfig
/tmp/aa/zephyr/boards/arm/olimex_lora_stm32wl_devkit/olimex_lora_stm32wl_devkit_defconfig
/tmp/aa/zephyr/boards/arm/nuvoton_pfm_m487/nuvoton_pfm_m487_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_wl55jc/nucleo_wl55jc_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_wb55rg/nucleo_wb55rg_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_u575zi_q/nucleo_u575zi_q_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l552ze_q/nucleo_l552ze_q_ns_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l552ze_q/nucleo_l552ze_q_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l4r5zi/nucleo_l4r5zi_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l496zg/nucleo_l496zg_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l476rg/nucleo_l476rg_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l452re/nucleo_l452re_p_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l452re/nucleo_l452re_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l433rc_p/nucleo_l433rc_p_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l432kc/nucleo_l432kc_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l412rb_p/nucleo_l412rb_p_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l152re/nucleo_l152re_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l073rz/nucleo_l073rz_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l053r8/nucleo_l053r8_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l031k6/nucleo_l031k6_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_l011k4/nucleo_l011k4_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_h7a3zi_q/nucleo_h7a3zi_q_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_h753zi/nucleo_h753zi_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_h745zi_q/nucleo_h745zi_q_m7_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_h745zi_q/nucleo_h745zi_q_m4_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_h743zi/nucleo_h743zi_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_h723zg/nucleo_h723zg_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_g474re/nucleo_g474re_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_g431rb/nucleo_g431rb_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_g0b1re/nucleo_g0b1re_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_g071rb/nucleo_g071rb_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_g031k8/nucleo_g031k8_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f767zi/nucleo_f767zi_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f756zg/nucleo_f756zg_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f746zg/nucleo_f746zg_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f446ze/nucleo_f446ze_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f446re/nucleo_f446re_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f429zi/nucleo_f429zi_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f413zh/nucleo_f413zh_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f412zg/nucleo_f412zg_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f411re/nucleo_f411re_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f410rb/nucleo_f410rb_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f401re/nucleo_f401re_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f334r8/nucleo_f334r8_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f303re/nucleo_f303re_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f303k8/nucleo_f303k8_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f302r8/nucleo_f302r8_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f207zg/nucleo_f207zg_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f103rb/nucleo_f103rb_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f091rc/nucleo_f091rc_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f070rb/nucleo_f070rb_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f031k6/nucleo_f031k6_defconfig
/tmp/aa/zephyr/boards/arm/nucleo_f030r8/nucleo_f030r8_defconfig
/tmp/aa/zephyr/boards/arm/nrf9160dk_nrf9160/nrf9160dk_nrf9160_ns_defconfig
/tmp/aa/zephyr/boards/arm/nrf9160dk_nrf9160/nrf9160dk_nrf9160_defconfig
/tmp/aa/zephyr/boards/arm/nrf9160dk_nrf52840/nrf9160dk_nrf52840_defconfig
/tmp/aa/zephyr/boards/arm/nrf9160_innblue22/nrf9160_innblue22_ns_defconfig
/tmp/aa/zephyr/boards/arm/nrf9160_innblue22/nrf9160_innblue22_defconfig
/tmp/aa/zephyr/boards/arm/nrf9160_innblue21/nrf9160_innblue21_ns_defconfig
/tmp/aa/zephyr/boards/arm/nrf9160_innblue21/nrf9160_innblue21_defconfig
/tmp/aa/zephyr/boards/arm/nrf5340dk_nrf5340/nrf5340dk_nrf5340_cpunet_defconfig
/tmp/aa/zephyr/boards/arm/nrf5340dk_nrf5340/nrf5340dk_nrf5340_cpuapp_ns_defconfig
/tmp/aa/zephyr/boards/arm/nrf5340dk_nrf5340/nrf5340dk_nrf5340_cpuapp_defconfig
/tmp/aa/zephyr/boards/arm/nrf52dk_nrf52832/nrf52dk_nrf52832_defconfig
/tmp/aa/zephyr/boards/arm/nrf52dk_nrf52810/nrf52dk_nrf52810_defconfig
/tmp/aa/zephyr/boards/arm/nrf52dk_nrf52805/nrf52dk_nrf52805_defconfig
/tmp/aa/zephyr/boards/arm/nrf52_vbluno52/nrf52_vbluno52_defconfig
/tmp/aa/zephyr/boards/arm/nrf52_sparkfun/nrf52_sparkfun_defconfig
/tmp/aa/zephyr/boards/arm/nrf52_blenano2/nrf52_blenano2_defconfig
/tmp/aa/zephyr/boards/arm/nrf52_adafruit_feather/nrf52_adafruit_feather_defconfig
/tmp/aa/zephyr/boards/arm/nrf52840dongle_nrf52840/nrf52840dongle_nrf52840_defconfig
/tmp/aa/zephyr/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840_defconfig
/tmp/aa/zephyr/boards/arm/nrf52840dk_nrf52811/nrf52840dk_nrf52811_defconfig
/tmp/aa/zephyr/boards/arm/nrf52840_papyr/nrf52840_papyr_defconfig
/tmp/aa/zephyr/boards/arm/nrf52840_mdk_usb_dongle/nrf52840_mdk_usb_dongle_defconfig
/tmp/aa/zephyr/boards/arm/nrf52840_mdk/nrf52840_mdk_defconfig
/tmp/aa/zephyr/boards/arm/nrf52840_blip/nrf52840_blip_defconfig
/tmp/aa/zephyr/boards/arm/nrf52833dk_nrf52833/nrf52833dk_nrf52833_defconfig
/tmp/aa/zephyr/boards/arm/nrf52833dk_nrf52820/nrf52833dk_nrf52820_defconfig
/tmp/aa/zephyr/boards/arm/nrf52832_mdk/nrf52832_mdk_defconfig
/tmp/aa/zephyr/boards/arm/nrf51dongle_nrf51422/nrf51dongle_nrf51422_defconfig
/tmp/aa/zephyr/boards/arm/nrf51dk_nrf51422/nrf51dk_nrf51422_defconfig
/tmp/aa/zephyr/boards/arm/nrf51_vbluno51/nrf51_vbluno51_defconfig
/tmp/aa/zephyr/boards/arm/nrf51_blenano/nrf51_blenano_defconfig
/tmp/aa/zephyr/boards/arm/nrf51_ble400/nrf51_ble400_defconfig
/tmp/aa/zephyr/boards/arm/nrf21540dk_nrf52840/nrf21540dk_nrf52840_defconfig
/tmp/aa/zephyr/boards/arm/npcx9m6f_evb/npcx9m6f_evb_defconfig
/tmp/aa/zephyr/boards/arm/npcx7m6fb_evb/npcx7m6fb_evb_defconfig
/tmp/aa/zephyr/boards/arm/msp_exp432p401r_launchxl/msp_exp432p401r_launchxl_defconfig
/tmp/aa/zephyr/boards/arm/mps3_an547/mps3_an547_ns_defconfig
/tmp/aa/zephyr/boards/arm/mps3_an547/mps3_an547_defconfig
/tmp/aa/zephyr/boards/arm/mps2_an521/mps2_an521_remote_defconfig
/tmp/aa/zephyr/boards/arm/mps2_an521/mps2_an521_ns_defconfig
/tmp/aa/zephyr/boards/arm/mps2_an521/mps2_an521_defconfig
/tmp/aa/zephyr/boards/arm/mps2_an385/mps2_an385_defconfig
/tmp/aa/zephyr/boards/arm/mm_swiftio/mm_swiftio_defconfig
/tmp/aa/zephyr/boards/arm/mm_feather/mm_feather_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt685_evk/mimxrt685_evk_cm33_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt595_evk/mimxrt595_evk_cm33_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1170_evk/mimxrt1170_evk_cm7_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1170_evk/mimxrt1170_evk_cm4_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1160_evk/mimxrt1160_evk_cm7_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1160_evk/mimxrt1160_evk_cm4_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1064_evk/mimxrt1064_evk_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1060_evk/mimxrt1060_evkb_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1060_evk/mimxrt1060_evk_hyperflash_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1060_evk/mimxrt1060_evk_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1050_evk/mimxrt1050_evk_qspi_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1050_evk/mimxrt1050_evk_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1024_evk/mimxrt1024_evk_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1020_evk/mimxrt1020_evk_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1015_evk/mimxrt1015_evk_defconfig
/tmp/aa/zephyr/boards/arm/mimxrt1010_evk/mimxrt1010_evk_defconfig
/tmp/aa/zephyr/boards/arm/mimx8mq_evk/mimx8mq_evk_cm4_defconfig
/tmp/aa/zephyr/boards/arm/mimx8mp_evk/mimx8mp_evk_itcm_defconfig
/tmp/aa/zephyr/boards/arm/mimx8mp_evk/mimx8mp_evk_ddr_defconfig
/tmp/aa/zephyr/boards/arm/mimx8mm_evk/mimx8mm_evk_defconfig
/tmp/aa/zephyr/boards/arm/mikroe_mini_m4_for_stm32/mikroe_mini_m4_for_stm32_defconfig
/tmp/aa/zephyr/boards/arm/mikroe_clicker_2/mikroe_clicker_2_defconfig
/tmp/aa/zephyr/boards/arm/mercury_xu/mercury_xu_defconfig
/tmp/aa/zephyr/boards/arm/mec2016evb_assy6797/mec2016evb_assy6797_defconfig
/tmp/aa/zephyr/boards/arm/mec172xevb_assy6906/mec172xevb_assy6906_defconfig
/tmp/aa/zephyr/boards/arm/mec15xxevb_assy6853/mec15xxevb_assy6853_defconfig
/tmp/aa/zephyr/boards/arm/mec1501modular_assy6885/mec1501modular_assy6885_defconfig
/tmp/aa/zephyr/boards/arm/lpcxpresso55s69/lpcxpresso55s69_ns_defconfig
/tmp/aa/zephyr/boards/arm/lpcxpresso55s69/lpcxpresso55s69_cpu1_defconfig
/tmp/aa/zephyr/boards/arm/lpcxpresso55s69/lpcxpresso55s69_cpu0_defconfig
/tmp/aa/zephyr/boards/arm/lpcxpresso55s36/lpcxpresso55s36_defconfig
/tmp/aa/zephyr/boards/arm/lpcxpresso55s28/lpcxpresso55s28_defconfig
/tmp/aa/zephyr/boards/arm/lpcxpresso55s16/lpcxpresso55s16_defconfig
/tmp/aa/zephyr/boards/arm/lpcxpresso55s06/lpcxpresso55s06_defconfig
/tmp/aa/zephyr/boards/arm/lpcxpresso54114/lpcxpresso54114_m4_defconfig
/tmp/aa/zephyr/boards/arm/lpcxpresso54114/lpcxpresso54114_m0_defconfig
/tmp/aa/zephyr/boards/arm/lpcxpresso51u68/lpcxpresso51u68_defconfig
/tmp/aa/zephyr/boards/arm/lpcxpresso11u68/lpcxpresso11u68_defconfig
/tmp/aa/zephyr/boards/arm/lora_e5_dev_board/lora_e5_dev_board_defconfig
/tmp/aa/zephyr/boards/arm/legend/legend_defconfig
/tmp/aa/zephyr/boards/arm/ip_k66f/ip_k66f_defconfig
/tmp/aa/zephyr/boards/arm/holyiot_yj16019/holyiot_yj16019_defconfig
/tmp/aa/zephyr/boards/arm/hexiwear_kw40z/hexiwear_kw40z_defconfig
/tmp/aa/zephyr/boards/arm/hexiwear_k64/hexiwear_k64_defconfig
/tmp/aa/zephyr/boards/arm/google_kukui/google_kukui_defconfig
/tmp/aa/zephyr/boards/arm/gd32f470i_eval/gd32f470i_eval_defconfig
/tmp/aa/zephyr/boards/arm/gd32f450z_eval/gd32f450z_eval_defconfig
/tmp/aa/zephyr/boards/arm/gd32f450v_start/gd32f450v_start_defconfig
/tmp/aa/zephyr/boards/arm/gd32f450i_eval/gd32f450i_eval_defconfig
/tmp/aa/zephyr/boards/arm/gd32f407v_start/gd32f407v_start_defconfig
/tmp/aa/zephyr/boards/arm/gd32f403z_eval/gd32f403z_eval_defconfig
/tmp/aa/zephyr/boards/arm/gd32f350r_eval/gd32f350r_eval_defconfig
/tmp/aa/zephyr/boards/arm/gd32e507z_eval/gd32e507z_eval_defconfig
/tmp/aa/zephyr/boards/arm/gd32e507v_start/gd32e507v_start_defconfig
/tmp/aa/zephyr/boards/arm/gd32e103v_eval/gd32e103v_eval_defconfig
/tmp/aa/zephyr/boards/arm/fvp_baser_aemv8r_aarch32/fvp_baser_aemv8r_aarch32_defconfig
/tmp/aa/zephyr/boards/arm/frdm_kw41z/frdm_kw41z_defconfig
/tmp/aa/zephyr/boards/arm/frdm_kl25z/frdm_kl25z_defconfig
/tmp/aa/zephyr/boards/arm/frdm_k82f/frdm_k82f_defconfig
/tmp/aa/zephyr/boards/arm/frdm_k64f/frdm_k64f_defconfig
/tmp/aa/zephyr/boards/arm/frdm_k22f/frdm_k22f_defconfig
/tmp/aa/zephyr/boards/arm/faze/faze_defconfig
/tmp/aa/zephyr/boards/arm/efr32mg_sltb004a/efr32mg_sltb004a_defconfig
/tmp/aa/zephyr/boards/arm/efr32_radio/efr32_radio_brd4255a_defconfig
/tmp/aa/zephyr/boards/arm/efr32_radio/efr32_radio_brd4250b_defconfig
/tmp/aa/zephyr/boards/arm/efr32_radio/efr32_radio_brd4180a_defconfig
/tmp/aa/zephyr/boards/arm/efr32_radio/efr32_radio_brd4104a_defconfig
/tmp/aa/zephyr/boards/arm/efm32wg_stk3800/efm32wg_stk3800_defconfig
/tmp/aa/zephyr/boards/arm/efm32pg_stk3402a/efm32pg_stk3402a_jg_defconfig
/tmp/aa/zephyr/boards/arm/efm32pg_stk3402a/efm32pg_stk3402a_defconfig
/tmp/aa/zephyr/boards/arm/efm32pg_stk3401a/efm32pg_stk3401a_defconfig
/tmp/aa/zephyr/boards/arm/efm32hg_slstk3400a/efm32hg_slstk3400a_defconfig
/tmp/aa/zephyr/boards/arm/efm32gg_stk3701a/efm32gg_stk3701a_defconfig
/tmp/aa/zephyr/boards/arm/efm32gg_slwstk6121a/efm32gg_slwstk6121a_defconfig
/tmp/aa/zephyr/boards/arm/ebyte_e73_tbb_nrf52832/ebyte_e73_tbb_nrf52832_defconfig
/tmp/aa/zephyr/boards/arm/dragino_nbsn95/dragino_nbsn95_defconfig
/tmp/aa/zephyr/boards/arm/dragino_lsn50/dragino_lsn50_defconfig
/tmp/aa/zephyr/boards/arm/disco_l475_iot1/disco_l475_iot1_defconfig
/tmp/aa/zephyr/boards/arm/degu_evk/degu_evk_defconfig
/tmp/aa/zephyr/boards/arm/decawave_dwm1001_dev/decawave_dwm1001_dev_defconfig
/tmp/aa/zephyr/boards/arm/da1469x_dk_pro/da1469x_dk_pro_defconfig
/tmp/aa/zephyr/boards/arm/cyclonev_socdk/cyclonev_socdk_defconfig
/tmp/aa/zephyr/boards/arm/cy8ckit_062_wifi_bt/cy8ckit_062_wifi_bt_m4_defconfig
/tmp/aa/zephyr/boards/arm/cy8ckit_062_wifi_bt/cy8ckit_062_wifi_bt_m0_defconfig
/tmp/aa/zephyr/boards/arm/cy8ckit_062_ble/cy8ckit_062_ble_m4_defconfig
/tmp/aa/zephyr/boards/arm/cy8ckit_062_ble/cy8ckit_062_ble_m0_defconfig
/tmp/aa/zephyr/boards/arm/contextualelectronics_abc/contextualelectronics_abc_defconfig
/tmp/aa/zephyr/boards/arm/colibri_imx7d_m4/colibri_imx7d_m4_defconfig
/tmp/aa/zephyr/boards/arm/circuitdojo_feather_nrf9160/circuitdojo_feather_nrf9160_ns_defconfig
/tmp/aa/zephyr/boards/arm/circuitdojo_feather_nrf9160/circuitdojo_feather_nrf9160_defconfig
/tmp/aa/zephyr/boards/arm/cc3235sf_launchxl/cc3235sf_launchxl_defconfig
/tmp/aa/zephyr/boards/arm/cc3220sf_launchxl/cc3220sf_launchxl_defconfig
/tmp/aa/zephyr/boards/arm/cc26x2r1_launchxl/cc26x2r1_launchxl_defconfig
/tmp/aa/zephyr/boards/arm/cc1352r_sensortag/cc1352r_sensortag_defconfig
/tmp/aa/zephyr/boards/arm/cc1352r1_launchxl/cc1352r1_launchxl_defconfig
/tmp/aa/zephyr/boards/arm/bt610/bt610_defconfig
/tmp/aa/zephyr/boards/arm/bt510/bt510_defconfig
/tmp/aa/zephyr/boards/arm/blueclover_plt_demo_v2_nrf52832/blueclover_plt_demo_v2_nrf52832_defconfig
/tmp/aa/zephyr/boards/arm/blackpill_f411ce/blackpill_f411ce_defconfig
/tmp/aa/zephyr/boards/arm/blackpill_f401ce/blackpill_f401ce_defconfig
/tmp/aa/zephyr/boards/arm/blackpill_f401cc/blackpill_f401cc_defconfig
/tmp/aa/zephyr/boards/arm/black_f407zg_pro/black_f407zg_pro_defconfig
/tmp/aa/zephyr/boards/arm/black_f407ve/black_f407ve_defconfig
/tmp/aa/zephyr/boards/arm/bl654_usb/bl654_usb_defconfig
/tmp/aa/zephyr/boards/arm/bl654_sensor_board/bl654_sensor_board_defconfig
/tmp/aa/zephyr/boards/arm/bl654_dvk/bl654_dvk_defconfig
/tmp/aa/zephyr/boards/arm/bl653_dvk/bl653_dvk_defconfig
/tmp/aa/zephyr/boards/arm/bl652_dvk/bl652_dvk_defconfig
/tmp/aa/zephyr/boards/arm/bl5340_dvk/bl5340_dvk_cpunet_defconfig
/tmp/aa/zephyr/boards/arm/bl5340_dvk/bl5340_dvk_cpuapp_ns_defconfig
/tmp/aa/zephyr/boards/arm/bl5340_dvk/bl5340_dvk_cpuapp_defconfig
/tmp/aa/zephyr/boards/arm/bcm958402m2_m7/bcm958402m2_m7_defconfig
/tmp/aa/zephyr/boards/arm/bcm958401m2/bcm958401m2_defconfig
/tmp/aa/zephyr/boards/arm/bbc_microbit_v2/bbc_microbit_v2_defconfig
/tmp/aa/zephyr/boards/arm/bbc_microbit/bbc_microbit_defconfig
/tmp/aa/zephyr/boards/arm/b_u585i_iot02a/b_u585i_iot02a_ns_defconfig
/tmp/aa/zephyr/boards/arm/b_u585i_iot02a/b_u585i_iot02a_defconfig
/tmp/aa/zephyr/boards/arm/b_l4s5i_iot01a/b_l4s5i_iot01a_defconfig
/tmp/aa/zephyr/boards/arm/b_l072z_lrwan1/b_l072z_lrwan1_defconfig
/tmp/aa/zephyr/boards/arm/b_g474e_dpow1/b_g474e_dpow1_defconfig
/tmp/aa/zephyr/boards/arm/atsamr34_xpro/atsamr34_xpro_defconfig
/tmp/aa/zephyr/boards/arm/atsamr21_xpro/atsamr21_xpro_defconfig
/tmp/aa/zephyr/boards/arm/atsaml21_xpro/atsaml21_xpro_defconfig
/tmp/aa/zephyr/boards/arm/atsame54_xpro/atsame54_xpro_defconfig
/tmp/aa/zephyr/boards/arm/atsamd21_xpro/atsamd21_xpro_defconfig
/tmp/aa/zephyr/boards/arm/atsamd20_xpro/atsamd20_xpro_defconfig
/tmp/aa/zephyr/boards/arm/ast1030_evb/ast1030_evb_defconfig
/tmp/aa/zephyr/boards/arm/arty/arty_a7_arm_designstart_m3_defconfig
/tmp/aa/zephyr/boards/arm/arty/arty_a7_arm_designstart_m1_defconfig
/tmp/aa/zephyr/boards/arm/arduino_zero/arduino_zero_defconfig
/tmp/aa/zephyr/boards/arm/arduino_nicla_sense_me/arduino_nicla_sense_me_defconfig
/tmp/aa/zephyr/boards/arm/arduino_nano_33_iot/arduino_nano_33_iot_defconfig
/tmp/aa/zephyr/boards/arm/arduino_nano_33_ble/arduino_nano_33_ble_sense_defconfig
/tmp/aa/zephyr/boards/arm/arduino_nano_33_ble/arduino_nano_33_ble_defconfig
/tmp/aa/zephyr/boards/arm/arduino_mkrzero/arduino_mkrzero_defconfig
/tmp/aa/zephyr/boards/arm/arduino_due/arduino_due_defconfig
/tmp/aa/zephyr/boards/arm/adafruit_trinket_m0/adafruit_trinket_m0_defconfig
/tmp/aa/zephyr/boards/arm/adafruit_itsybitsy_m4_express/adafruit_itsybitsy_m4_express_defconfig
/tmp/aa/zephyr/boards/arm/adafruit_feather_stm32f405/adafruit_feather_stm32f405_defconfig
/tmp/aa/zephyr/boards/arm/adafruit_feather_nrf52840/adafruit_feather_nrf52840_defconfig
/tmp/aa/zephyr/boards/arm/adafruit_feather_m0_basic_proto/adafruit_feather_m0_basic_proto_defconfig
/tmp/aa/zephyr/boards/arm/actinius_icarus_som/actinius_icarus_som_ns_defconfig
/tmp/aa/zephyr/boards/arm/actinius_icarus_som/actinius_icarus_som_defconfig
/tmp/aa/zephyr/boards/arm/actinius_icarus_bee/actinius_icarus_bee_ns_defconfig
/tmp/aa/zephyr/boards/arm/actinius_icarus_bee/actinius_icarus_bee_defconfig
/tmp/aa/zephyr/boards/arm/actinius_icarus/actinius_icarus_ns_defconfig
/tmp/aa/zephyr/boards/arm/actinius_icarus/actinius_icarus_defconfig
/tmp/aa/zephyr/boards/arm/96b_wistrio/96b_wistrio_defconfig
/tmp/aa/zephyr/boards/arm/96b_stm32_sensor_mez/96b_stm32_sensor_mez_defconfig
/tmp/aa/zephyr/boards/arm/96b_nitrogen/96b_nitrogen_defconfig
/tmp/aa/zephyr/boards/arm/96b_neonkey/96b_neonkey_defconfig
/tmp/aa/zephyr/boards/arm/96b_meerkat96/96b_meerkat96_defconfig
/tmp/aa/zephyr/boards/arm/96b_carbon_nrf51/96b_carbon_nrf51_defconfig
/tmp/aa/zephyr/boards/arm/96b_carbon/96b_carbon_defconfig
/tmp/aa/zephyr/boards/arm/96b_avenger96/96b_avenger96_defconfig
/tmp/aa/zephyr/boards/arm/96b_argonkey/96b_argonkey_defconfig
/tmp/aa/zephyr/boards/arm/96b_aerocore2/96b_aerocore2_defconfig
/tmp/aa/zephyr/boards/arc/qemu_arc/qemu_arc_hs_defconfig
/tmp/aa/zephyr/boards/arc/qemu_arc/qemu_arc_hs6x_defconfig
/tmp/aa/zephyr/boards/arc/qemu_arc/qemu_arc_hs5x_defconfig
/tmp/aa/zephyr/boards/arc/qemu_arc/qemu_arc_em_defconfig
/tmp/aa/zephyr/boards/arc/nsim/nsim_sem_mpu_stack_guard_defconfig
/tmp/aa/zephyr/boards/arc/nsim/nsim_sem_defconfig
/tmp/aa/zephyr/boards/arc/nsim/nsim_hs_smp_defconfig
/tmp/aa/zephyr/boards/arc/nsim/nsim_hs_mpuv6_defconfig
/tmp/aa/zephyr/boards/arc/nsim/nsim_hs_defconfig
/tmp/aa/zephyr/boards/arc/nsim/nsim_hs6x_smp_defconfig
/tmp/aa/zephyr/boards/arc/nsim/nsim_hs6x_defconfig
/tmp/aa/zephyr/boards/arc/nsim/nsim_hs5x_smp_defconfig
/tmp/aa/zephyr/boards/arc/nsim/nsim_hs5x_defconfig
/tmp/aa/zephyr/boards/arc/nsim/nsim_em_defconfig
/tmp/aa/zephyr/boards/arc/nsim/nsim_em7d_v22_defconfig
/tmp/aa/zephyr/boards/arc/iotdk/iotdk_defconfig
/tmp/aa/zephyr/boards/arc/hsdk/hsdk_defconfig
/tmp/aa/zephyr/boards/arc/hsdk/hsdk_2cores_defconfig
/tmp/aa/zephyr/boards/arc/emsdp/emsdp_em9d_defconfig
/tmp/aa/zephyr/boards/arc/emsdp/emsdp_em7d_esp_defconfig
/tmp/aa/zephyr/boards/arc/emsdp/emsdp_em7d_defconfig
/tmp/aa/zephyr/boards/arc/emsdp/emsdp_em6_defconfig
/tmp/aa/zephyr/boards/arc/emsdp/emsdp_em5d_defconfig
/tmp/aa/zephyr/boards/arc/emsdp/emsdp_em4_defconfig
/tmp/aa/zephyr/boards/arc/emsdp/emsdp_defconfig
/tmp/aa/zephyr/boards/arc/em_starterkit/em_starterkit_em7d_v22_defconfig
/tmp/aa/zephyr/boards/arc/em_starterkit/em_starterkit_em7d_defconfig
/tmp/aa/zephyr/boards/arc/em_starterkit/em_starterkit_em11d_defconfig
/tmp/aa/zephyr/boards/arc/em_starterkit/em_starterkit_defconfig
");

foreach ($boards as $ThisBoard)
{
	if (strlen($ThisBoard) > 8)
	{
		$Update = false;
		$Dat = explode("\n", file_get_contents($ThisBoard));
		$DatA = array();
		foreach ($Dat as $ThisID => $ThisRow)
		{
			if (strpos($ThisRow, "CONFIG_SOC_") !== false)
			{
				$DatA[] = $ThisRow;
				unset($Dat[$ThisID]);
				$Update = true;
			}
		}

		if ($Update == true)
		{
			$DatA = implode("\n", $DatA);
			$fp = fopen(substr($ThisBoard, 0, (strlen($ThisBoard) - 9)).'soc', 'w');
			fwrite($fp, "# SPDX-License-Identifier: Apache-2.0\n");
			fwrite($fp, $DatA."\n");
			fclose($fp);

			$Dat = implode("\n", $Dat);
			$fp = fopen($ThisBoard, 'w');
			fwrite($fp, $Dat);
			fclose($fp);
		}
	}
}
?>

