#
set(SYSBUILD_CURRENT_MODULE_NAME TEST_APP)
set(SYSBUILD_CURRENT_MODULE_DIR ${CMAKE_CURRENT_LIST_DIR}/sysbuild)
set(SYSBUILD_CURRENT_CMAKE_DIR ${CMAKE_CURRENT_LIST_DIR}/sysbuild)
set(SYSBUILD_MODULE_NAMES ${SYSBUILD_MODULE_NAMES} ${SYSBUILD_CURRENT_MODULE_NAME})
add_subdirectory(${SYSBUILD_CURRENT_CMAKE_DIR} ${CMAKE_BINARY_DIR}/modules/${SYSBUILD_CURRENT_MODULE_NAME})

# Add the swapped app to the build
ExternalZephyrProject_Add(
  APPLICATION smp_svr
  SOURCE_DIR ${ZEPHYR_BASE}/samples/subsys/mgmt/mcumgr/smp_svr
)

set(IMAGES ${IMAGES} smp_svr)
