
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:28 (project)"
    message: |
      The system is: Linux - 6.8.1-zen1-1-zen - x86_64
...
